# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='General notes', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='reg_notes',
            field=models.CharField(blank=True, default='', help_text='Registration notes', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='General notes', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='reg_notes',
            field=models.CharField(blank=True, default='', help_text='Registration notes', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvisit',
            name='visited_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
