# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='household',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='household',
        ),
        migrations.AddField(
            model_name='client',
            name='reg_notes',
            field=models.TextField(blank=True, default='', help_text='Registration notes'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='reg_notes',
            field=models.TextField(blank=True, default='', help_text='Registration notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='newId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='General notes'),
        ),
        migrations.AlterField(
            model_name='client',
            name='oldId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('NEW', 'New client'), ('TMP', 'Temp ID issued'), ('APP', 'Application submitted'), ('REG', 'Registered')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='newId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='General notes'),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='oldId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='photo',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='status',
            field=models.CharField(choices=[('NEW', 'New client'), ('TMP', 'Temp ID issued'), ('APP', 'Application submitted'), ('REG', 'Registered')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='address',
            field=models.CharField(blank=True, help_text='Street Address', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='historicalhousehold',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='address',
            field=models.CharField(blank=True, help_text='Street Address', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of Birth', null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
