# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170904_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalclient',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalclient',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='historicaldependent',
            name='dependent_on',
        ),
        migrations.RemoveField(
            model_name='historicaldependent',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldependent',
            name='person_ptr',
        ),
        migrations.RemoveField(
            model_name='historicalvisit',
            name='client',
        ),
        migrations.RemoveField(
            model_name='historicalvisit',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalvisit',
            name='picked_up_by',
        ),
        migrations.DeleteModel(
            name='HistoricalClient',
        ),
        migrations.DeleteModel(
            name='HistoricalDependent',
        ),
        migrations.DeleteModel(
            name='HistoricalVisit',
        ),
    ]
