# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20170827_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='TempId',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='TempId',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='newId',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='oldId',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='newId',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalclient',
            name='oldId',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
